; PlatformIO projekt — Pametno navodnjavanje (IoT_21221)
; Pokretanje u VS Code (PlatformIO) ili preko CLI-a:  pio run
; Simulacija u VS Code: Wokwi ekstenzija (wokwi.toml)

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

; Wokwi simulacija koristi ovaj firmware
build_flags =
    -DCORE_DEBUG_LEVEL=0

lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.5


